### ISSUE TITLE
Queues UI bug

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#20] opened 2016-10-12 16:57 UTC
### :bug:

this is what happens when i scroll up & down queues listview having most number videos for download

![screenshot 8](https://cloud.githubusercontent.com/assets/14979775/19319550/f1017842-90ca-11e6-9bba-4e7e19cd0f7f.png)

sometime i get this

![screenshot 9](https://cloud.githubusercontent.com/assets/14979775/19319652/6a43ee74-90cb-11e6-9f8f-f05828445f81.png)

**Comment by AlexxEG** [comment] 2016-10-12 20:03
Any idea how I can reproduce this?

**Comment by ObaidGH** [comment] 2016-10-13 06:15
Refer to this issue #18

**Comment by AlexxEG** [comment] 2016-10-13 22:23
I'll look more into this when I start merging the UI change from #18, but you can try enabling double buffering.

**Comment by ObaidGH** [comment] 2016-10-14 05:09
Double buffering is already set to true

**Comment by AlexxEG** [comment] 2016-10-18 07:45
I'm gonna close this since I'm working on replacing the ListView with ObjectListView, which should not have this problem.

**Closed as completed by AlexxEG** 2016-10-18 07:45 UTC
Labels: bug
